### ISSUE TITLE
Documents similarity algorithm fails with NegativeArraySizeException on 20M documents input

### ISSUE THREAD

**Issue by marekhorst** [CeON/CoAnSys#425]
Originally reported in OpenAIRE redmine ticket: [#2976](https://issue.openaire.research-infrastructures.eu/issues/2976).

After the total number of publications increased from 18M to 21M documents similarity algorithm crashed on mapreduce reducing phase with the following exception:
```
java.lang.NegativeArraySizeException
    at org.apache.hadoop.mapred.IFile$Reader.nextRawValue(IFile.java:436)
    at org.apache.hadoop.mapred.Merger$Segment.nextRawValue(Merger.java:341)
    at org.apache.hadoop.mapred.Merger$Segment.getValue(Merger.java:323)
    at org.apache.hadoop.mapred.Merger$MergeQueue.next(Merger.java:567)
    at org.apache.hadoop.mapred.ReduceTask$4.next(ReduceTask.java:601)
    at org.apache.hadoop.mapreduce.task.ReduceContextImpl.<init>(ReduceContextImpl.java:105)
    at org.apache.hadoop.mapred.Task.createReduceContext(Task.java:1529)
    at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:619)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:422)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```
indicating int variable (most probably `IFile$Reader$currentValueLength`) overflow.

Quick solution is limiting docsim input by adjusting `sample` input parameter. Changing from `1.0` to `0.9` means randomly selected 90% of input records will be taken into account.

**Comment by marekhorst** [comment]
After deeper inspection it turned out the exception occurs during PIG `rank` operation performed over set of terms from all publications:
```
wc_rankedX = rank wc by count asc;
```
but the real cause of the problem starts [two lines above](https://github.com/CeON/CoAnSys/blob/298863befc2f0e3a96b25a9ee53f6b53b41090a6/document-similarity/document-similarity-logic/src/main/pig/document-similarity-s1-rank_filter.pig#L127):
```
group_by_terms = group doc_all by term;
wc = foreach group_by_terms generate COUNT(doc_all) as count, group as term, doc_all.docId as docs;
```
where all terms are grouped by `term`. This means all `docId`s associated with given term are grouped together. 

Here is the top 10 of stemmed terms with the most numerous group of `docId`s:
```
(8008493,studi)
(5362545,model)
(5305067,result)
(4478170,effect)
(4422744,system)
(4384836,cell)
(4177665,gener)
(4103819,develop)
(3836632,research)
(3796164,scienc)
```
which means over 8M of document identifiers (OpenAIRE id is ~50 chars long) are stored in single `wc` entry's field being `rank`ed later on.

One working solution is excluding `docId`s from grouping and ranking operations:
```
wc = foreach group_by_terms generate COUNT(terms) as count, group as term;
```
where `group_by_terms` should not be generated from `doc_all` but reused from [line 117](https://github.com/CeON/CoAnSys/blob/298863befc2f0e3a96b25a9ee53f6b53b41090a6/document-similarity/document-similarity-logic/src/main/pig/document-similarity-s1-rank_filter.pig#L117).

and joining document identifiers later on:
```
term_condition_accepted_tmp_joined_with_docs = join term_condition_accepted_tmp by term, doc_all by term;
doc_selected_termsX = foreach term_condition_accepted_tmp_joined_with_docs generate doc_all::docId, doc_all::term;

```
replacing already existing line [142](https://github.com/CeON/CoAnSys/blob/298863befc2f0e3a96b25a9ee53f6b53b41090a6/document-similarity/document-similarity-logic/src/main/pig/document-similarity-s1-rank_filter.pig#L142):
```
doc_selected_termsX = foreach term_condition_accepted_tmp generate FLATTEN(docs) as docId, term;
```

Pull request will be issued soon.
